micronaut:
    application:
        name: barn-automation-service-micronaut-groovy
    server:
        cors:
            enabled: true
    io:
        watch:
            paths: src/main
            restart: true